mybatis:
  type-aliases-package: cn.hsiangsun.beans
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weTalk?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1314
    driver-class-name: com.mysql.jdbc.Driver