mybatis:
  type-aliases-package: cn.hsiangsun.beans
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/weTalk?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: root